// This file is auto-generated by @hey-api/openapi-ts

export const ConsultationCreateSchema = {
    properties: {
        patient_full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Patient Full Name'
        },
        doctor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doctor Id'
        },
        notes: {
            type: 'string',
            title: 'Notes',
            default: ''
        },
        diagnosis_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Diagnosis Ids',
            default: []
        }
    },
    type: 'object',
    required: ['patient_full_name'],
    title: 'ConsultationCreate'
} as const;

export const ConsultationReadSchema = {
    properties: {
        patient_full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Patient Full Name'
        },
        doctor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Doctor Id'
        },
        notes: {
            type: 'string',
            title: 'Notes',
            default: ''
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        diagnoses: {
            items: {
                '$ref': '#/components/schemas/DiagnosisRead'
            },
            type: 'array',
            title: 'Diagnoses'
        }
    },
    type: 'object',
    required: ['patient_full_name', 'id', 'created_at', 'diagnoses'],
    title: 'ConsultationRead'
} as const;

export const DiagnosisReadSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 10,
            title: 'Code'
        },
        description: {
            type: 'string',
            maxLength: 255,
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['code', 'description', 'id', 'created_at'],
    title: 'DiagnosisRead'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LoginRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'LoginRequest'
} as const;

export const QueryResult_ConsultationRead_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ConsultationRead'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'QueryResult[ConsultationRead]'
} as const;

export const QueryResult_DiagnosisRead_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DiagnosisRead'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'QueryResult[DiagnosisRead]'
} as const;

export const QueryResult_UserRead_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserRead'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'QueryResult[UserRead]'
} as const;

export const RoleSchema = {
    type: 'string',
    enum: ['admin', 'doctor'],
    title: 'Role'
} as const;

export const TokenResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['access_token', 'expires_in'],
    title: 'TokenResponse'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/Role',
            default: 'doctor'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserReadSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/Role',
            default: 'doctor'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserRead'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;