// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AuthLoginData, AuthLoginResponse, AuthRefreshResponse, AuthLogoutResponse, ConsultationCreateConsultationData, ConsultationCreateConsultationResponse, ConsultationListConsultationsData, ConsultationListConsultationsResponse, ConsultationGetConsultationData, ConsultationGetConsultationResponse, DiagnosisSearchDiagnosesData, DiagnosisSearchDiagnosesResponse, RootRootResponse, RootHealthCheckResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse } from './types.gen';

export class AuthService {
    /**
     * Login
     * Login with email and password.
     * Returns access token and sets refresh token in an HTTP-only cookie.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns TokenResponse Successful Response
     * @throws ApiError
     */
    public static login(data: AuthLoginData): CancelablePromise<AuthLoginResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/login',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Refresh
     * Refresh access token using the refresh token from cookie.
     * @returns TokenResponse Successful Response
     * @throws ApiError
     */
    public static refresh(): CancelablePromise<AuthRefreshResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/refresh'
        });
    }
    
    /**
     * Logout
     * Logout by blacklisting the current tokens and clearing the cookie.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static logout(): CancelablePromise<AuthLogoutResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/logout'
        });
    }
}

export class ConsultationService {
    /**
     * Create Consultation
     * Create a new consultation record.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ConsultationRead Successful Response
     * @throws ApiError
     */
    public static createConsultation(data: ConsultationCreateConsultationData): CancelablePromise<ConsultationCreateConsultationResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/consultation/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Consultations
     * List consultations. Doctors only see their own, Admins see all.
     * @param data The data for the request.
     * @param data.skip Number of records to skip
     * @param data.limit Maximum records to return
     * @param data.sort Sort field. Prefix with - for descending (e.g., '-created_at')
     * @param data.search Search query for text fields
     * @returns QueryResult_ConsultationRead_ Successful Response
     * @throws ApiError
     */
    public static listConsultations(data: ConsultationListConsultationsData = {}): CancelablePromise<ConsultationListConsultationsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/consultation/',
            query: {
                skip: data.skip,
                limit: data.limit,
                sort: data.sort,
                search: data.search
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Consultation
     * Get detailed consultation info. Doctors can only access their own records.
     * @param data The data for the request.
     * @param data.consultationId
     * @returns ConsultationRead Successful Response
     * @throws ApiError
     */
    public static getConsultation(data: ConsultationGetConsultationData): CancelablePromise<ConsultationGetConsultationResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/consultation/{consultation_id}',
            path: {
                consultation_id: data.consultationId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class DiagnosisService {
    /**
     * Search Diagnoses
     * Search for diagnosis codes by code.
     * @param data The data for the request.
     * @param data.skip Number of records to skip
     * @param data.limit Maximum records to return
     * @param data.sort Sort field. Prefix with - for descending (e.g., '-created_at')
     * @param data.search Search query for text fields
     * @returns QueryResult_DiagnosisRead_ Successful Response
     * @throws ApiError
     */
    public static searchDiagnoses(data: DiagnosisSearchDiagnosesData = {}): CancelablePromise<DiagnosisSearchDiagnosesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/diagnosis/',
            query: {
                skip: data.skip,
                limit: data.limit,
                sort: data.sort,
                search: data.search
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class RootService {
    /**
     * Root
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static root(): CancelablePromise<RootRootResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/'
        });
    }
    
    /**
     * Health Check
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<RootHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health'
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     *
     * Requires: admin role
     * @param data The data for the request.
     * @param data.skip Number of records to skip
     * @param data.limit Maximum records to return
     * @param data.sort Sort field. Prefix with - for descending (e.g., '-created_at')
     * @param data.search Search query for text fields
     * @returns QueryResult_UserRead_ Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit,
                sort: data.sort,
                search: data.search
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create a new user.
     *
     * Requires: admin role
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserRead Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}