// This file is auto-generated by @hey-api/openapi-ts

export type ConsultationCreate = {
    patient_full_name: string;
    doctor_id?: (string | null);
    consultation_date: string;
    notes?: string;
    diagnosis_ids?: Array<(string)>;
};

export type ConsultationList = {
    id: string;
    patient_full_name: string;
    doctor_name: string;
    consultation_date: string;
    created_at: string;
    diagnosis_count: number;
    diagnoses: Array<DiagnosisRead>;
};

export type ConsultationRead = {
    patient_full_name: string;
    doctor_id?: (string | null);
    consultation_date: string;
    notes?: string;
    id: string;
    created_at: string;
    doctor_name?: (string | null);
    diagnoses: Array<DiagnosisRead>;
};

export type DiagnosisRead = {
    code: string;
    description: string;
    id: string;
    created_at: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type QueryResult_ConsultationList_ = {
    data: Array<ConsultationList>;
    count: number;
};

export type QueryResult_DiagnosisRead_ = {
    data: Array<DiagnosisRead>;
    count: number;
};

export type QueryResult_UserRead_ = {
    data: Array<UserRead>;
    count: number;
};

export type Role = 'admin' | 'doctor';

export type TokenResponse = {
    access_token: string;
    token_type?: string;
    expires_in: number;
};

export type UserCreate = {
    email: string;
    full_name?: (string | null);
    role?: Role;
    is_active?: boolean;
    password: string;
};

export type UserRead = {
    email: string;
    full_name?: (string | null);
    role?: Role;
    is_active?: boolean;
    id: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuthLoginData = {
    requestBody: LoginRequest;
};

export type AuthLoginResponse = (TokenResponse);

export type AuthRefreshResponse = (TokenResponse);

export type AuthLogoutResponse = (unknown);

export type ConsultationCreateConsultationData = {
    requestBody: ConsultationCreate;
};

export type ConsultationCreateConsultationResponse = (ConsultationRead);

export type ConsultationListConsultationsData = {
    /**
     * Maximum records to return
     */
    limit?: number;
    /**
     * Search query for text fields
     */
    search?: (string | null);
    /**
     * Number of records to skip
     */
    skip?: number;
    /**
     * Sort field. Prefix with - for descending (e.g., '-created_at')
     */
    sort?: string;
};

export type ConsultationListConsultationsResponse = (QueryResult_ConsultationList_);

export type ConsultationGetConsultationData = {
    consultationId: string;
};

export type ConsultationGetConsultationResponse = (ConsultationRead);

export type DiagnosisSearchDiagnosesData = {
    /**
     * Maximum records to return
     */
    limit?: number;
    /**
     * Search query for text fields
     */
    search?: (string | null);
    /**
     * Number of records to skip
     */
    skip?: number;
    /**
     * Sort field. Prefix with - for descending (e.g., '-created_at')
     */
    sort?: string;
};

export type DiagnosisSearchDiagnosesResponse = (QueryResult_DiagnosisRead_);

export type RootRootResponse = (unknown);

export type RootHealthCheckResponse = (unknown);

export type UsersReadUserMeResponse = (UserRead);

export type UsersReadUsersData = {
    /**
     * Maximum records to return
     */
    limit?: number;
    /**
     * Search query for text fields
     */
    search?: (string | null);
    /**
     * Number of records to skip
     */
    skip?: number;
    /**
     * Sort field. Prefix with - for descending (e.g., '-created_at')
     */
    sort?: string;
};

export type UsersReadUsersResponse = (QueryResult_UserRead_);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserRead);