"""consultation date field

Revision ID: 9b61ffd50773
Revises: b9b0a350c3e2
Create Date: 2026-02-16 23:33:37.403659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b61ffd50773'
down_revision: Union[str, Sequence[str], None] = 'b9b0a350c3e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add the column as nullable first to avoid IntegrityError with existing data
    op.add_column('consultation', sa.Column('consultation_date', sa.DateTime(), nullable=True))
    
    # 2. Populate existing rows with a default value (using created_at as a proxy)
    op.execute("UPDATE consultation SET consultation_date = created_at")
    
    # 3. Finally, enforce NOT NULL constraint
    op.alter_column('consultation', 'consultation_date', nullable=False)
    op.create_index(op.f('ix_consultation_consultation_date'), 'consultation', ['consultation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_consultation_date'), table_name='consultation')
    op.drop_column('consultation', 'consultation_date')
    # ### end Alembic commands ###
