"""consultation model

Revision ID: b9b0a350c3e2
Revises: 0768f35f64c2
Create Date: 2026-02-16 16:08:46.472019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b9b0a350c3e2'
down_revision: Union[str, Sequence[str], None] = '0768f35f64c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation',
    sa.Column('patient_full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('doctor_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultation_diagnoses',
    sa.Column('consultation_id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultation.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis.id'], ),
    sa.PrimaryKeyConstraint('consultation_id', 'diagnosis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultation_diagnoses')
    op.drop_table('consultation')
    # ### end Alembic commands ###
